spring:
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    url: ${ICRITIC_DB_URL:jdbc:postgresql://localhost:5432/icritic}
    username: ${ICRITIC_DB_USERNAME:root}
    password: ${ICRITIC_DB_PASSWORD:root}
  jpa:
    database: POSTGRESQL
server:
  port: 8083
  error:
    include-stacktrace: never