spring:
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    url: ${ICRITIC_DB_URL:jdbc:postgresql://localhost:5432/icritic}
    username: ${ICRITIC_DB_USERNAME:root}
    password: ${ICRITIC_DB_PASSWORD:root}
  jpa:
    database: POSTGRESQL
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
server:
  port: 8083
  error:
    include-stacktrace: never
application:
  properties:
    services:
      icritic-users-service-address: ${ICRITIC_USERS_SERVICE_ADDRESS:http://localhost:8081}
